USE [OnlineAdmission]
GO

/****** Object:  Table [dbo].[STUDENT_DETAILS]    Script Date: 4/17/2016 4:22:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STUDENT_DETAILS](
	[APPLICATION_ID] [int] IDENTITY(1000,1) NOT NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[MIDDLE_NAME] [varchar](50) NULL,
	[SURNAME] [varchar](50) NULL,
	[GENDER] [varchar](10) NULL,
	[MOTHER_TONGUE] [varchar](50) NULL,
	[RELIGION] [varchar](50) NULL,
	[CASTE_SUB_CASTE] [varchar](50) NULL,
	[PLACE_OF_BIRTH] [varchar](50) NULL,
	[DATE_OF_BIRTH] [date] NULL,
	[RESIDENTIAL_ADDRESS] [varchar](max) NULL,
	[AREA] [varchar](20) NULL,
	[AADHAR_NUMBER] [varchar](20) NULL,
	[MEDICAL_HISTORY] [varchar](max) NULL,
	[ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[FATHERS_NAME] [varchar](50) NULL,
	[FATHERS_QUALIFICATION] [varchar](50) NULL,
	[FATHERS_OCCUPATION] [varchar](50) NULL,
	[FATHERS_NATIVE_PLACE] [varchar](50) NULL,
	[FATHERS_EMAIL] [varchar](50) NULL,
	[FATHERS_TELEPHONE] [varchar](20) NULL,
	[FATHERS_MOBILE_NUMBER] [varchar](20) NULL,
	[FATHERS_WHATSAPP_NUMBER] [varchar](20) NULL,
	[FATHERS_RESIDENTIAL_ADDRESS] [varchar](max) NULL,
	[FATHERS_OFFICE_ADDRESS] [varchar](max) NULL,
	[FATHERS_OFFICE_TELEPHONE_NUMBER] [varchar](20) NULL,
	[FATHERS_PAN_NUMBER] [varchar](20) NULL,
	[FATHERS_AADHAR_NUMBER] [varchar](20) NULL,
	[MOTHERS_NAME] [varchar](50) NULL,
	[MOTHERS_MAIDEN_NAME] [varchar](50) NULL,
	[MOTHERS_QUALIFICATION] [varchar](50) NULL,
	[MOTHERS_OCCUPATION] [varchar](50) NULL,
	[MOTHERS_NATIVE_PLACE] [varchar](50) NULL,
	[MOTHERS_EMAIL] [varchar](50) NULL,
	[MOTHERS_TELEPHONE] [varchar](20) NULL,
	[MOTHERS_MOBILE_NUMBER] [varchar](20) NULL,
	[MOTHERS_WHATSAPP_NUMBER] [varchar](20) NULL,
	[MOTHERS_RESIDENTIAL_ADDRESS] [varchar](max) NULL,
	[MOTHERS_OFFICE_ADDRESS] [varchar](max) NULL,
	[MOTHERS_OFFICE_TELEPHONE_NUMBER] [varchar](20) NULL,
	[MOTHERS_PAN_NUMBER] [varchar](20) NULL,
	[MOTHERS_AADHAR_NUMBER] [varchar](20) NULL,
	[RELATION_IN_SCHOOL] [varchar](10) NULL,
	[RELATION_NAME] [varchar](50) NULL,
	[RELATION_SECTION] [varchar](20) NULL,
	[RELATION_STANDARD] [varchar](20) NULL,
	[RELATION_DIVISION] [varchar](20) NULL,
	[FAMILY_INCOME] [varchar](20) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


